---
debug: debug # fatal, error, warn, info, debug; defaults to 'fatal'
logfile: stderr # stderr, stdout, or path; defaults to log/ongorora.log
title: Ongorora
theme: cosmo # One of cerulean cosmo cyborg darkly flatly journal lumen paper readable sandstone simplex slate spacelab superhero united yeti (see http://bootswatch.com). Leave empty for default
port: # Specify a port where you can reach the webinterface, or (default) 4567

# see lib/analyzer/database
database:
  backend: elasticsearch
  url: http://localhost:9200

elasticsearch:
  index: "elasticsupport"
